version: "3.9"
volumes:
  openbis-state:
services:
  openbis:
    image: openbis/debian-openbis:20.10.5-EA
    environment:
      - SERVER_HOST_PORT=localhost:8443
      - GROUP_ID=1000
      - CORE_PLUGINS=enabled-modules = dataset-uploader, dataset-file-search, xls-import, eln-lims, openbis-ng-ui, search-store, user-management-maintenance
    volumes:      
    #Openbis state
      - openbis-state:/home/openbis/openbis_state/
    ports:
      - 8443:443
    hostname: openbis
  app:
    build: ./frontend/
    volumes:
      - ./frontend/app:/usr/app
    ports:
      - 8080:5173