version: "3.9"
volumes:
  openbis-state:
services:
  openbis:
    image: openbis/debian-openbis:20.10.5-EA
    environment:
      - SERVER_HOST_PORT=localhost:8443
      - GROUP_ID=1000
      - CORE_PLUGINS=enabled-modules = dataset-uploader, dataset-file-search, xls-import, eln-lims, openbis-ng-ui, search-store, user-management-maintenance
    volumes:      
    #Openbis state
      - openbis-state:/home/openbis/openbis_state/
      - ./openbis/service.properties:/home/openbis/openbis_state/as_etc/service.properties
    ports:
      - 8445:443
    hostname: openbis
    healthcheck:
      test: ["CMD", "curl", "openbis:443"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  openbis-intialiser:
    depends_on:
      openbis:
        condition: service_healthy
    build: ./configurator
    volumes:
      - ./configurator/instance.json:/usr/src/app/instance.json
  app:
    build: ./frontend/
    volumes:
      - ./frontend/app:/usr/app
    ports:
      - 8081:5173
      - 8082:4173