/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package cleaner

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertFails
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import cleaner.chemicals.CAS
import cleaner.openbis.OpenbisPropertyMapping



class AppTest {

    @Test fun testCASTooLong(){
        assertFails({CAS.fromString("12-3-3-4")})
    }

    @Test fun testValidCAS(){
        assertEquals(CAS.fromString("10026-04-7").toCASString(), "10026-04-7")
    }

    @Test fun testOpenbisObjectMapping(){
        val fields = mapOf<String, String>("a" to "a", "b" to "b")
        val objectMapping = OpenbisPropertyMapping(fields)
        val mapped = objectMapping.transformMap(mapOf("c" to "d"))
        assertEquals(mapped, emptyMap())
    }
}
